package:
  name: lancaster
  version: {{ GIT_DESCRIBE_TAG }}
 
source:
  git_url: ../..

requirements:
  build:
    - python
    - setuptools
    - libavro
  run:
    - python
    - libavro

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{py}}_{% if GIT_DESCRIBE_NUMBER != '0' %}{{ GIT_BUILD_STR }}{% else %}0{% endif %}

  script:
    - python setup.py install

test:
  requires:
    - avro-python3
    - pytest
  files:
    - ../../lancaster/tests/test_bench.py
  commands:
    - py.test -v

about:
  home: https://github.com/twosigma/lancaster
  license: MIT
  license_file: LICENSE
